#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            caches:
              - pip
            script:
              - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              - pip install coverage pytest
              - pip install numpy
              - coverage run -m pytest -v --junitxml=test-reports/report.xml tests/
        - step:
            name: Lint code
            script:
              # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
              - pip install flake8
              - flake8 . --extend-exclude=dist,build,playgrounds --ignore=E701,E402,E731,E501,E711,W293,F401,E741 --show-source --statistics
        - step:
            image: node
            name: NPM
            script:
              - cd app
              - apt-get install python3-pip -y
              - pip3 install virtualenv
              - npm run init
              - timeout 2m npm run dev
